// TYPES_NODE
export const UPDATE_PUBLIC_COURSES = "store/UPDATE_PUBLIC_COURSES";
export const UPDATE_PRIVATE_COURSES = "store/UPDATE_PRIVATE_COURSES";
export const SAVE_USERS = "store/SAVE_USERS";
export const CURRENT_USER = "store/CURRENT_USER";

// ACTIONS_NODE
export const ACTION_UPDATE_PUBLIC_COURSES = "store/ACTION_UPDATE_PUBLIC_COURSES";
export const ACTION_UPDATE_PRIVATE_COURSES = "store/ACTION_UPDATE_PRIVATE_COURSES";
export const ACTION_SAVE_USERS = "store/ACTION_SAVE_USERS";
export const ACTION_CURRENT_USER = "store/ACTION_CURRENT_USER";