// TYPES_NODE
export const IS_USER_LOGGED_IN = "store/IS_USER_LOGGED_IN";
export const IS_ADMIN_LOGGED_IN = "store/IS_ADMIN_LOGGED_IN";

// ACTIONS_NODE
export const ACTION_IS_USER_LOGGED_IN = "store/ACTION_IS_USER_LOGGED_IN";
export const ACTION_IS_ADMIN_LOGGED_IN = "store/ACTION_IS_ADMIN_LOGGED_IN";